name: stuverse
description: Stuverse student and alumni community forum
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.4.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^13.0.1
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/logo/stuverse.jpg"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app/logo/stuverse.jpg"
    background_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/app/logo/stuverse.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app/logo/stuverse.jpg"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app/
    - assets/app/logo/
    - assets/common/
    - assets/forum/
    - assets/fund/
    - assets/job/
    - assets/mentor/
