name: stuverse
description: Stuverse student and alumni community forum
version: 1.0.1+9
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_tree_view: ^2.2.0
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  confetti: ^0.7.0
  device_preview: ^1.1.0
  dio: ^5.4.0
  dropdown_search: ^5.0.6
  easy_search_bar: ^2.5.0
  expandable: ^5.0.1
  file_picker: ^6.1.1
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.20
  flutter_native_splash: ^2.3.10
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logman: ^0.0.13
  lottie: ^3.1.0
  permission_handler: ^11.3.0
  readmore: ^2.2.0
  share_plus: ^8.0.2
  shared_preferences: ^2.2.2
  skeletonizer: ^1.0.1
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_pdfviewer: ^24.2.8
  url_launcher: ^6.2.5
  web_socket_channel: ^2.4.0
  webview_flutter: ^4.7.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/app/animations/
    - assets/app/icons/
    - assets/app/logo/
    - assets/app/images/
    - assets/forum/icons/
    - assets/forum/images/
    - assets/fund/icons/
    - assets/fund/images/
    - assets/job/icons/
    - assets/job/images/
    - assets/mentor/icons/
    - assets/mentor/images/

flutter_native_splash:
  color: "#000B18"
  image: assets/app/logo/stuverse.png
  color_dark: "#000B18"
  image_dark: assets/app/logo/stuverse.png

  android_12:
    image: assets/app/logo/stuverse.png
    icon_background_color: "#000B18"
    image_dark: assets/app/logo/stuverse.png
    icon_background_color_dark: "#000B18"

  web: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/logo/stuverse.jpg"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app/logo/stuverse.jpg"
    background_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/app/logo/stuverse.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app/logo/stuverse.jpg"
