name: stuverse
description: Stuverse student and alumni community forum
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  device_preview: ^1.1.0
  dio: ^5.4.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/app/icons/
    - assets/app/logo/
    - assets/common/
    - assets/forum/
    - assets/fund/
    - assets/job/
    - assets/mentor/





flutter_native_splash:
  color: "#000B18"
  image: assets/app/logo/stuverse.png
  color_dark: "#000B18"
  image_dark: assets/app/logo/stuverse.png


  android_12:
    image: assets/app/logo/stuverse.png
    icon_background_color: "#000B18"
    image_dark: assets/app/logo/stuverse.png
    icon_background_color_dark: "#000B18"

  web: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/logo/stuverse.jpg"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app/logo/stuverse.jpg"
    background_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/app/logo/stuverse.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app/logo/stuverse.jpg"

