// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF3z0U6hRftdmIsvtLHl0UlZwzzKpR-9Y',
    appId: '1:395933211284:web:184d46beb11744db4a7281',
    messagingSenderId: '395933211284',
    projectId: 'stuverse-project',
    authDomain: 'stuverse-project.firebaseapp.com',
    storageBucket: 'stuverse-project.appspot.com',
    measurementId: 'G-D11CEXVDH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFMCq-46f8w7LEHzAek2th0RqYilg3PYc',
    appId: '1:395933211284:android:469f87ae76f212244a7281',
    messagingSenderId: '395933211284',
    projectId: 'stuverse-project',
    storageBucket: 'stuverse-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI9r7-834iehI_xr-NbaE-9xAL01sKj6w',
    appId: '1:395933211284:ios:f539a06212efabd04a7281',
    messagingSenderId: '395933211284',
    projectId: 'stuverse-project',
    storageBucket: 'stuverse-project.appspot.com',
    iosBundleId: 'in.stuverse.stuverse',
  );
}
